spring:
  datasource:
    testdb:
      url: "jdbc:mysql://localhost:3306/testdb"
      driver-class-name: "com.mysql.cj.jdbc.Driver"
      username: "admin"
      password: "password"
    testdb2:
      url: "jdbc:mysql://localhost:3307/testdb"
      driver-class-name: "com.mysql.cj.jdbc.Driver"
      username: "admin"
      password: "password"

server.port: 8081
